/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JFrame;

/**
 *
 * @author Marcos
 */
public class ViewTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewTelaPrincipal
     */
    public ViewTelaPrincipal() {
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Tela principal abrir maximizada
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnClientesTelaPrincipal = new javax.swing.JButton();
        jbtnUsuariosTelaPrincipal = new javax.swing.JButton();
        jbtnProdutos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmenuSobre = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmenuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmenuClientes = new javax.swing.JMenuItem();
        jmenuUsuarios = new javax.swing.JMenuItem();
        jmenuProdutos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Vendas ");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\telainicial_bateria.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\telainicialk_microfone.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\menuinicial_guitarra.png")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jbtnClientesTelaPrincipal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnClientesTelaPrincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\botaoinicial_cliente.png")); // NOI18N
        jbtnClientesTelaPrincipal.setText("Clientes");
        jbtnClientesTelaPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnClientesTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClientesTelaPrincipalActionPerformed(evt);
            }
        });

        jbtnUsuariosTelaPrincipal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnUsuariosTelaPrincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\botãoinicial_usuarios.png")); // NOI18N
        jbtnUsuariosTelaPrincipal.setText("Usuarios");
        jbtnUsuariosTelaPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnUsuariosTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUsuariosTelaPrincipalActionPerformed(evt);
            }
        });

        jbtnProdutos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnProdutos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\botaomenu_produtos.png")); // NOI18N
        jbtnProdutos.setText("Produtos");
        jbtnProdutos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProdutosActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\shop2.png")); // NOI18N
        jButton1.setText("Vendas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jbtnProdutos)
                    .addComponent(jbtnUsuariosTelaPrincipal)
                    .addComponent(jbtnClientesTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jbtnClientesTelaPrincipal, jbtnProdutos, jbtnUsuariosTelaPrincipal});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jbtnClientesTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnUsuariosTelaPrincipal)
                .addGap(18, 18, 18)
                .addComponent(jbtnProdutos)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnClientesTelaPrincipal, jbtnProdutos, jbtnUsuariosTelaPrincipal});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\telainicial_violao.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41))))
        );

        jMenu1.setText("Arquivos");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jmenuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmenuSobre.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\menu_sobre.png")); // NOI18N
        jmenuSobre.setText("Sobre");
        jmenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuSobreActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuSobre);
        jMenu1.add(jSeparator1);

        jmenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmenuSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\menu_sair.png")); // NOI18N
        jmenuSair.setText("Sair");
        jmenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuSairActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastros");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jmenuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmenuClientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\menu_clientes2.png")); // NOI18N
        jmenuClientes.setText("Clientes");
        jmenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuClientesActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuClientes);

        jmenuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmenuUsuarios.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\menu_usuarios2.png")); // NOI18N
        jmenuUsuarios.setText("Usuários");
        jmenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuUsuarios);

        jmenuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmenuProdutos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\menu_produtos3.png")); // NOI18N
        jmenuProdutos.setText("Produtos");
        jmenuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuProdutos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vendas");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Documents\\NetBeansProjects\\SVendas\\src\\main\\resoucers\\shop3.png")); // NOI18N
        jMenuItem1.setText("Vendas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuClientesActionPerformed
        new ViewCliente().setVisible(true); // chamar cadastro de clientes
    }//GEN-LAST:event_jmenuClientesActionPerformed

    private void jmenuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuProdutosActionPerformed
        new ViewProduto().setVisible(true); // chamar cadastro de produtos
    }//GEN-LAST:event_jmenuProdutosActionPerformed

    private void jmenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuSairActionPerformed
        System.exit(0); // sair do sistema
    }//GEN-LAST:event_jmenuSairActionPerformed

    private void jmenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuSobreActionPerformed

    private void jbtnClientesTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClientesTelaPrincipalActionPerformed
        new ViewCliente().setVisible(true); // chamar cadastro de clientes
    }//GEN-LAST:event_jbtnClientesTelaPrincipalActionPerformed

    private void jmenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuUsuariosActionPerformed
         new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_jmenuUsuariosActionPerformed

    private void jbtnUsuariosTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUsuariosTelaPrincipalActionPerformed
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_jbtnUsuariosTelaPrincipalActionPerformed

    private void jbtnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProdutosActionPerformed
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_jbtnProdutosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ViewVendas().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new ViewVendas().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jbtnClientesTelaPrincipal;
    private javax.swing.JButton jbtnProdutos;
    private javax.swing.JButton jbtnUsuariosTelaPrincipal;
    private javax.swing.JMenuItem jmenuClientes;
    private javax.swing.JMenuItem jmenuProdutos;
    private javax.swing.JMenuItem jmenuSair;
    private javax.swing.JMenuItem jmenuSobre;
    private javax.swing.JMenuItem jmenuUsuarios;
    // End of variables declaration//GEN-END:variables
}
